  host: noemiamccarthy-web-basics-hand-in-04.idp.laurinnotemann.dev
  image: europe-west10-docker.pkg.dev/code-idp/idp-artifact-registry/noemiamccarthy-web-basics-hand-in-04:d59fe176d6615b0178927ed73eeda2ed16e35457
  name: noemiamccarthy-web-basics-hand-in-04
