apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}-service
  namespace: {{ .Release.Namespace }}
  labels: 
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 3000
      name: container-port
      targetPort: container-port