name: "initial-image-build-workflow"

on:
  workflow_dispatch: # Put here!!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
