name: "initial-image-build-workflow"

on:
  # Trigger a specific workflow run on demand without need for a code push/pull request
  workflow_dispatch:
    inputs:
      githubRepo:
        description: "Link of public github repo to deploy"
        required: true
    inputs:
      githubRepo:
        description: "Link of public github repo to deploy"
        required: true

jobs:
  create_submodule:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: create_student_submodule
        name: Add student's repo as a submodule
        run: |
          echo "YEAR=$(date '+%Y')" >> $GITHUB_ENV
          echo "USER_NAME=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f4)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f5)" >> $GITHUB_ENV

          year=$(date '+%Y')
          user_name=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f4)
          repo_name=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f5)

          if [ ! -d submissions-${year} ]; then
            mkdir submissions-${year}
          fi

          if [ ! -d submissions-${year}/${user_name}-${repo_name} ]; then
            echo "Adding ${{ github.event.inputs.githubRepo }} to ./submissions-${year}/${user_name}-${repo_name}/${user_name}-${repo_name} as a submodule"

            git config --global user.name github-actions
            git config --global user.email github-actions@github.com

            cd ./submissions-${year}
            mkdir ${user_name}-${repo_name}
            cd ./${user_name}-${repo_name}

            git submodule add ${{ github.event.inputs.githubRepo }} ./${user_name}-${repo_name}
            git commit -m "Added ${user_name}-${repo_name} as a submodule by github-actions"
            git push

            echo "STATUS=$(echo 'success')" >> $GITHUB_ENV
          else
            echo "Submodule already exists, terminating github actions"
            echo "STATUS=$(echo 'failure')" >> $GITHUB_ENV

          fi

    outputs:
      status: ${{ env.STATUS }}
      year: ${{ env.YEAR }}
      user_name: ${{ env.USER_NAME }}
      repo_name: ${{ env.REPO_NAME }}

  get_repository_dependencies:
    needs: create_submodule
    permissions:
      contents: "write"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    if: needs.create_submodule.outputs.status == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull the changes made in the repository.
        run: git pull --recurse-submodules

      - id: output_values
        name: Prepare the outputs for the next job
        run: |
          cd ./submissions-${{ needs.create_submodule.outputs.year }}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}

          git submodule update --init --recursive

          YEAR="$(date '+%Y')"
          USER_NAME=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f4)
          REPO_NAME=$(echo "${{ github.event.inputs.githubRepo }}" | cut -d'/' -f5)
          SHA_VALUE="$(git submodule status | awk '{print $1}')"

          echo "year: ${YEAR}"
          echo "user_name: ${USER_NAME}"
          echo "repo_name: ${REPO_NAME}"
          echo "sha_value: ${SHA_VALUE}"

          echo "YEAR=$YEAR" >> "$GITHUB_OUTPUT"
          echo "USER_NAME=$USER_NAME" >> "$GITHUB_OUTPUT"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_OUTPUT"
          echo "SHA_VALUE=$SHA_VALUE" >> "$GITHUB_OUTPUT"

      - id: extracting_dependencies
        name: Get submodule's dependencies
        run: |

          cd ./submissions-${{ needs.create_submodule.outputs.year }}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}

          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DEPENDENCY_GRAPH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ needs.create_submodule.outputs.user_name }}/${{ needs.create_submodule.outputs.repo_name }}/dependency-graph/sbom >> extracted_dependencies.json

          jq '.sbom.packages' extracted_dependencies.json >> extracted_packages.json

          jq ".[] | .name" extracted_packages.json >> package_names_list.txt  

          rm extracted_dependencies.json extracted_packages.json

      - name: Copy the docker file based on the repository dependencies
        run: |
          cd ./submissions-${{ needs.create_submodule.outputs.year }}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}/${{ needs.create_submodule.outputs.user_name }}-${{ needs.create_submodule.outputs.repo_name}}

          if  grep -q "npm:express" package_names_list.txt ; then
           echo "Copying Dockerfiles/nodejs/Dockerfile into repository"
           cp ../../../Dockerfiles/nodejs/Dockerfile . 
          elif grep -q "pip:flask" package_names_list.txt ; then
           echo "Copying Dockerfiles/flask/Dockerfile into repository"
           cp ../../../Dockerfiles/flask/Dockerfile .
          else
            echo "value does not exist!"
          fi

          rm package_names_list.txt

    outputs:
      current_commit_sha: ${{ steps.output_values.outputs.SHA_VALUE }}
      year: ${{ steps.output_values.outputs.YEAR }}
      user_name: ${{ steps.output_values.outputs.USER_NAME }}
      repo_name: ${{ steps.output_values.outputs.REPO_NAME }}
# need to add export DOCKER_BUILDKIT=1 before building python docker image
