name: "initial-image-build-workflow"

on:
  # Trigger a specific workflow run on demand without need for a code push/pull
  workflow_dispatch:
    # inputs:
    #   githubRepo:
    #     description: "Link of public github repo to deploy"
    #     required: true

jobs:
  create_docker_image:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Github dependents info
        run: pip install -U github-dependents-info


      - name: Check if directory exists
        run: |
          year=&(echo $(date '+%Y'))
          if [ -d submissions${year} ]; then
           echo "Directory exists"
          else
           echo "Directory does not exist"
          fi

# need to add export DOCKER_BUILDKIT=1 before building python docker image
